"""add_chat_sessions

Revision ID: e0671c685099
Revises: 2abc84cbeaea
Create Date: 2026-05-20 12:37:00.554179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0671c685099'
down_revision: Union[str, Sequence[str], None] = '2abc84cbeaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_messages', sa.Column('session_id', sa.Integer(), nullable=True))
    # A named constraint is required for a reversible PostgreSQL downgrade.
    # This is PostgreSQL's legacy default name as well, so the downgrade also
    # works for databases upgraded before the constraint was made explicit.
    op.create_foreign_key('chat_messages_session_id_fkey', 'chat_messages', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Backfill existing chat messages to a default session
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT DISTINCT user_id FROM chat_messages WHERE session_id IS NULL"))
    users_with_messages = [row[0] for row in result]
    
    for uid in users_with_messages:
        # Create a default session for this user
        insert_sess = sa.text(
            "INSERT INTO chat_sessions (user_id, title, created_at, updated_at) "
            "VALUES (:uid, 'Conversación Anterior', NOW(), NOW()) RETURNING id"
        )
        sess_id = bind.execute(insert_sess, {"uid": uid}).scalar()
        
        # Link all current messages of this user to this new session
        update_msgs = sa.text(
            "UPDATE chat_messages SET session_id = :sess_id WHERE user_id = :uid AND session_id IS NULL"
        )
        bind.execute(update_msgs, {"sess_id": sess_id, "uid": uid})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_session_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'session_id')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
